### ISSUE TITLE
KeyError during hasattr() call against AttrDict

### ISSUE THREAD

**Issue by mshriver** [mk-fg/layered-yaml-attrdict-config#12]
I am experiencing a KeyError within `AttrDict.__getattr__` when a `hasattr()` has been called against an AttrDict instance.

I believe that hasattr, calling getattr, is only capturing an AttributeError during this call stack, and `AttrDict.__getattr__` triggers a KeyError when the key is not double under prefixed or an OrderedDict key.

https://github.com/mk-fg/layered-yaml-attrdict-config/blob/master/lya/lya.py#L68

I believe an appropriate fix would be to catch the KeyError here and raise AttributeError instead, as hasattr is expecting.

**Comment by mk-fg** [comment]
Yes, I think it makes perfect sense to raise AttributeError there instead of KeyError.
I'll follow-up in a PR, thanks for raising the issue.
